# Generated by Django 6.0.3 on 2026-04-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cart_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
