# Generated by Django 6.0.3 on 2026-04-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cartitem_cart_date_cartitem_cart_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
