# Generated by Django 5.2.4 on 2026-04-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=10, unique=True)),
                ('area_name', models.CharField(max_length=120)),
                ('city', models.CharField(default='Nagpur', max_length=80)),
                ('state', models.CharField(default='Maharashtra', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('cod_allowed', models.BooleanField(default=True)),
                ('delivery_days', models.PositiveSmallIntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery Pincode',
                'verbose_name_plural': 'Delivery Pincodes',
                'ordering': ['pincode'],
            },
        ),
        migrations.CreateModel(
            name='DemandReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand_type', models.CharField(choices=[('product', 'Product Demand'), ('pincode', 'Pincode Demand'), ('category', 'Category Demand')], max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=120)),
                ('customer_phone', models.CharField(blank=True, max_length=15)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('product_name', models.CharField(blank=True, help_text='Fill if demand_type = product', max_length=200)),
                ('requested_pincode', models.CharField(blank=True, help_text='Fill if demand_type = pincode', max_length=10)),
                ('category_name', models.CharField(blank=True, help_text='Fill if demand_type = category', max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('in_progress', 'In Progress'), ('fulfilled', 'Fulfilled'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('admin_remarks', models.TextField(blank=True)),
                ('vote_count', models.PositiveIntegerField(default=1, help_text='How many customers want the same thing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Demand Report',
                'verbose_name_plural': 'Demand Reports',
                'ordering': ['-vote_count', '-created_at'],
            },
        ),
    ]
